build:
	clang++ -std=c++11 -L/opt/homebrew/Cellar/llvm/21.1.3/lib -llldb -I/opt/homebrew/Cellar/llvm/21.1.3/include main.cpp -o main.out
	clang++ -std=c++11 clean_up_outstanding_links.cpp -o clean.out