from typing import Final    # for marking constants

MEMORY_GRID_HEIGHT: Final = 800
MEMORY_GRID_WIDTH: Final = 800
MEMORY_GRID_SIDE_LENGTH: Final = 20

NUM_ROWS: Final = MEMORY_GRID_HEIGHT // MEMORY_GRID_SIDE_LENGTH
NUM_COLS: Final = MEMORY_GRID_WIDTH // MEMORY_GRID_SIDE_LENGTH

WORD_SIZE: Final = 8
HALF_WORD_SIZE: Final = WORD_SIZE // 2